-- =============================================================================
-- Migration 004 — Post-workout autoregulation survey
-- Paste into Supabase SQL Editor → Run
-- =============================================================================

ALTER TABLE public.workout_sessions
  ADD COLUMN IF NOT EXISTS survey_performance TEXT
    CHECK (survey_performance IN ('exceed', 'meet', 'miss')),
  ADD COLUMN IF NOT EXISTS survey_rir_feel TEXT
    CHECK (survey_rir_feel IN ('easier', 'on_target', 'too_hard')),
  ADD COLUMN IF NOT EXISTS survey_recovery TEXT
    CHECK (survey_recovery IN ('great', 'normal', 'sore')),
  -- Free-text recommendation generated by the decision tree; displayed
  -- as a toast at the top of the NEXT session in the same phase.
  ADD COLUMN IF NOT EXISTS next_week_suggestion TEXT;
